using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Sace.Api.Domain;
using Sace.Api.Infrastructure;
using Sace.Api.Services;
using Xunit;

namespace Sace.Api.Tests;

public class LegalAuditEngineTests {
  private sealed record Snapshot(LegalAuditSummary Summary, List<AuditResult> Results, List<Finding> Findings);

  [Fact] public async Task Pattern_case_reports_nine_compliant_one_not_applicable_and_one_manual() { var x=await Run(Pattern); Assert.Equal(9,x.Summary.Compliant); Assert.Equal(1,x.Summary.NotApplicable); Assert.Equal(1,x.Summary.ManualReview); Assert.Equal(100,x.Summary.AutomatedCompliancePercent); Assert.Equal(90,x.Summary.CoveragePercent); }
  [Fact] public async Task July_operation_selects_annex22_version_two() { var x=await Run(Pattern); Assert.Equal(2,Rule(x,"LEGAL-ANEXO22-INV-001").NormativeRuleVersion); }
  [Fact] public async Task February_operation_selects_annex22_version_one() { var x=await Run(Pattern,new DateTime(2026,2,1,0,0,0,DateTimeKind.Utc)); Assert.Equal(1,Rule(x,"LEGAL-ANEXO22-INV-001").NormativeRuleVersion); }
  [Fact] public async Task Future_rule_is_not_executed() { var x=await Run((db,op)=>db.NormativeRules.Add(Legal("LEGAL-FUTURE-TEST",new DateTime(2027,1,1,0,0,0,DateTimeKind.Utc)))); Assert.DoesNotContain(x.Results,r=>r.RuleId=="LEGAL-FUTURE-TEST"); }
  [Fact] public async Task Expired_rule_is_not_executed() { var x=await Run((db,op)=>db.NormativeRules.Add(Legal("LEGAL-EXPIRED-TEST",new DateTime(2025,1,1,0,0,0,DateTimeKind.Utc),new DateTime(2026,1,1,0,0,0,DateTimeKind.Utc)))); Assert.DoesNotContain(x.Results,r=>r.RuleId=="LEGAL-EXPIRED-TEST"); }
  [Fact] public async Task Demo_rules_do_not_enter_legal_results() { var x=await Run(null); Assert.DoesNotContain(x.Results,r=>r.RuleId.StartsWith("DEMO-")); }
  [Fact] public async Task Technical_rules_do_not_enter_legal_results() { var x=await Run(null); Assert.DoesNotContain(x.Results,r=>r.RuleId.StartsWith("TECH-")); }
  [Fact] public async Task Matching_pedimento_is_compliant() { var x=await Run((db,op)=>Doc(db,op,"PEDIMENTO","PED.xml",op.PedimentoNumber)); Assert.Equal(LegalOutcome.COMPLIANT,Rule(x,"LEGAL-LA36-001").Outcome); }
  [Fact] public async Task Mismatching_pedimento_is_non_compliant() { var x=await Run((db,op)=>Doc(db,op,"PEDIMENTO","PED.xml","OTRO")); Assert.Equal(LegalOutcome.NON_COMPLIANT,Rule(x,"LEGAL-LA36-001").Outcome); }
  [Fact] public async Task Invoice_threshold_applies_above_usd_300() { var x=await Run((db,op)=>{op.CommercialValue=301;op.Currency="USD";Doc(db,op,"COMMERCIAL_INVOICE","FAC.pdf","F-1");}); Assert.Equal(LegalOutcome.COMPLIANT,Rule(x,"LEGAL-RGCE-318-001").Outcome); }
  [Fact] public async Task Invoice_threshold_does_not_apply_at_usd_300() { var x=await Run((db,op)=>{op.CommercialValue=300;op.Currency="USD";}); Assert.Equal(LegalOutcome.NOT_APPLICABLE,Rule(x,"LEGAL-RGCE-318-001").Outcome); }
  [Fact] public async Task Structured_invoice_matches_operation() { var x=await Run((db,op)=>Invoice(db,op,"F-1","USD",4358.25m)); Assert.Equal(LegalOutcome.COMPLIANT,Rule(x,"LEGAL-ANEXO22-INV-001").Outcome); }
  [Fact] public async Task Structured_invoice_discrepancy_is_non_compliant() { var x=await Run((db,op)=>Invoice(db,op,"F-OTRA","USD",4358.25m)); Assert.Equal(LegalOutcome.NON_COMPLIANT,Rule(x,"LEGAL-ANEXO22-INV-001").Outcome); }
  [Fact] public async Task Matching_cove_references_are_compliant() { var x=await Run((db,op)=>Cove(db,op,"ABC123")); Assert.Equal(LegalOutcome.COMPLIANT,Rule(x,"LEGAL-RGCE-1916-001").Outcome); }
  [Fact] public async Task Mismatching_cove_references_are_non_compliant() { var x=await Run((db,op)=>Cove(db,op,"DIFFERENT")); Assert.Equal(LegalOutcome.NON_COMPLIANT,Rule(x,"LEGAL-RGCE-1916-001").Outcome); }
  [Fact] public async Task Missing_document_is_insufficient_evidence() { var x=await Run(null); Assert.Equal(LegalOutcome.INSUFFICIENT_EVIDENCE,Rule(x,"LEGAL-LA36-001").Outcome); }
  [Fact] public async Task Origin_rule_is_not_applicable_without_preference() { var x=await Run((db,op)=>op.PreferentialTreatment=false); Assert.Equal(LegalOutcome.NOT_APPLICABLE,Rule(x,"LEGAL-ORIGIN-001").Outcome); }
  [Fact] public async Task Rrna_is_always_manual_in_v1() { var x=await Run(null); Assert.Equal(LegalOutcome.MANUAL_REVIEW,Rule(x,"LEGAL-RRNA-001").Outcome); Assert.DoesNotContain(x.Findings,f=>f.RuleId=="LEGAL-RRNA-001"); }
  [Fact] public async Task Confirmed_incrementables_produce_compliant_calculation() { var x=await Run(ValueCorrect); Assert.Equal(LegalOutcome.COMPLIANT,Rule(x,"LEGAL-LA65-001").Outcome); }
  [Fact] public async Task Value_outside_tolerance_is_non_compliant_and_creates_finding() { var x=await Run((db,op)=>{ValueCorrect(db,op);op.DeclaredCustomsValueMxn=82000;}); Assert.Equal(LegalOutcome.NON_COMPLIANT,Rule(x,"LEGAL-LA65-001").Outcome); Assert.Contains(x.Findings,f=>f.RuleId=="LEGAL-LA65-001"); }
  [Fact] public async Task Manual_review_does_not_overwrite_automatic_outcome() {
    using var f=new SaceFactory(); var client=f.CreateClient(); var login=await client.PostAsJsonAsync("/api/auth/login",new{email="admin@sace.local",password="Admin123!"}); var token=JsonDocument.Parse(await login.Content.ReadAsStringAsync()).RootElement.GetProperty("token").GetString(); client.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",token);
    Guid resultId; using(var scope=f.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<SaceDbContext>();var op=NewOperation();db.TradeOperations.Add(op);await db.SaveChangesAsync();var engine=scope.ServiceProvider.GetRequiredService<ILegalAuditEngine>();var summary=await engine.ExecuteAsync(op.Id,(await db.Users.FirstAsync()).Id);resultId=await db.AuditResults.Where(x=>x.AuditId==summary.AuditId&&x.RuleId=="LEGAL-RRNA-001").Select(x=>x.Id).SingleAsync();}
    var response=await client.PostAsJsonAsync($"/api/audit-results/{resultId}/manual-review",new{manualOutcome="COMPLIANT",comment="Revisión documental completada por responsable."});response.EnsureSuccessStatusCode();using var check=f.Services.CreateScope();var saved=await check.ServiceProvider.GetRequiredService<SaceDbContext>().AuditResults.FindAsync(resultId);Assert.Equal(LegalOutcome.MANUAL_REVIEW,saved!.Outcome);Assert.Equal(LegalOutcome.COMPLIANT,saved.ManualOutcome);Assert.NotNull(saved.ReviewedAt);
  }

  private static async Task<Snapshot> Run(Action<SaceDbContext,TradeOperation>? setup,DateTime? date=null){using var f=new SaceFactory();_ = f.CreateClient();using var scope=f.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<SaceDbContext>();var op=NewOperation(date);db.TradeOperations.Add(op);await db.SaveChangesAsync();setup?.Invoke(db,op);await db.SaveChangesAsync();var engine=scope.ServiceProvider.GetRequiredService<ILegalAuditEngine>();var summary=await engine.ExecuteAsync(op.Id,(await db.Users.FirstAsync()).Id);var results=await db.AuditResults.AsNoTracking().Where(x=>x.AuditId==summary.AuditId).ToListAsync();var findings=await db.Findings.AsNoTracking().Where(x=>x.AuditId==summary.AuditId).ToListAsync();return new(summary,results,findings);}
  private static TradeOperation NewOperation(DateTime? date=null)=>new(){Folio=$"TEST-{Guid.NewGuid():N}",PedimentoNumber="26 48 1234 6002948",OperationDate=date??new DateTime(2026,7,19,0,0,0,DateTimeKind.Utc),Period="2026-07",OperationType=OperationType.Importacion,PedimentoKey="A1",TariffFraction="85044099",Nico="00",GoodsDescription="Fuente de alimentación",OriginCountry="Estados Unidos",DestinationCountry="México",CustomsRegime="Definitivo",InvoiceNumber="F-1",CommercialValue=4358.25m,Currency="USD",CoveNumber="ABC123",PreferentialTreatment=false};
  private static AuditResult Rule(Snapshot x,string code)=>x.Results.Single(r=>r.RuleId==code);
  private static NormativeRule Legal(string code,DateTime from,DateTime? to=null)=>new(){Code=code,Name=code,Description="Prueba",NormativeSource=NormativeSource.CustomsLaw,RuleCategory=RuleCategory.LEGAL,EffectiveFrom=from,EffectiveTo=to,IsLegalRule=true,IsIncludedInLegalCompliance=true,AutomationLevel=AutomationLevel.MANUAL};
  private static OperationDocument Doc(SaceDbContext db,TradeOperation op,string code,string name,string? number=null,string? metadata=null){var type=db.DocumentTypes.Single(x=>x.Code==code);var doc=new OperationDocument{TradeOperationId=op.Id,DocumentTypeId=type.Id,DocumentType=type,OriginalFileName=name,StoredFileName=name,MimeType="application/pdf",Extension=".pdf",FileSize=100,FilePath=$"test/{name}",ValidationStatus=ValidationStatus.Valid,UploadedBy=db.Users.Select(x=>x.Id).First(),DocumentNumber=number,ExtractedMetadataJson=metadata};db.OperationDocuments.Add(doc);op.Documents.Add(doc);return doc;}
  private static void Invoice(SaceDbContext db,TradeOperation op,string number,string currency,decimal total){op.InvoiceNumber="F-1";op.Currency="USD";op.CommercialValue=4358.25m;var meta=JsonSerializer.Serialize(new{documentNumber=number,date="2026-07-19",recipient="IMPORTADOR",description="Mercancía",quantity=1,supplier="PROVEEDOR",total=total.ToString(System.Globalization.CultureInfo.InvariantCulture),currency});Doc(db,op,"COMMERCIAL_INVOICE","invoice.pdf",number,meta);}
  private static void Cove(SaceDbContext db,TradeOperation op,string value){op.CoveNumber="ABC123";var doc=Doc(db,op,"COVE_ACK","cove.pdf",value);doc.References.Add(new DocumentReference{OperationDocument=doc,ReferenceType="COVE",Value=value,Source="COVE_ACK"});}
  private static void ValueCorrect(SaceDbContext db,TradeOperation op){op.CommercialValue=4358.25m;op.Currency="USD";op.ExchangeRate=18.5m;op.DeclaredCustomsValueMxn=82477.63m;db.CustomsValueAdjustments.Add(new CustomsValueAdjustment{TradeOperationId=op.Id,Concept="Flete",Amount=100m,Currency="USD",AdjustmentType=AdjustmentType.INCREMENTABLE,LegalQualificationStatus=LegalQualificationStatus.CONFIRMED});}
  private static void Pattern(SaceDbContext db,TradeOperation op){Doc(db,op,"PEDIMENTO","pedimento.xml",op.PedimentoNumber);Invoice(db,op,"F-1","USD",4358.25m);Cove(db,op,"ABC123");Doc(db,op,"TRANSPORT_DOCUMENT","transport.pdf","BL-001");var a=Doc(db,op,"EDOCUMENT_ACK","edoc-a.pdf");var b=Doc(db,op,"OTHER","edoc-b.pdf");a.References.Add(new DocumentReference{OperationDocument=a,ReferenceType="EDOCUMENT",Value="EDOC123",Source="acuse"});b.References.Add(new DocumentReference{OperationDocument=b,ReferenceType="EDOCUMENT",Value="EDOC123",Source="pedimento"});ValueCorrect(db,op);}
}
