using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using Xunit;

namespace Sace.Api.Tests;

public class RealDocumentTests {
  [Fact] public async Task Empty_xml_is_rejected() { using var f=new SaceFactory(); var c=await Client(f); var id=await DemoOperationId(c); var r=await Single(c,id,"empty.xml",[],"application/xml",await TypeId(c,"OTHER")); Assert.Equal(HttpStatusCode.BadRequest,r.StatusCode); Assert.Equal("EMPTY_FILE",(await Doc(r,false)).RootElement.GetProperty("code").GetString()); }
  [Fact] public async Task Malformed_xml_is_rejected() { using var f=new SaceFactory(); var c=await Client(f); var id=await DemoOperationId(c); var r=await Single(c,id,"bad.xml",Encoding.UTF8.GetBytes("<broken>"),"application/xml",await TypeId(c,"OTHER")); Assert.Equal("MALFORMED_XML",(await Doc(r,false)).RootElement.GetProperty("code").GetString()); }
  [Fact] public async Task Unsupported_file_is_rejected() { using var f=new SaceFactory(); var c=await Client(f); var id=await DemoOperationId(c); var r=await Single(c,id,"response.209","data"u8.ToArray(),"application/octet-stream",await TypeId(c,"OTHER")); Assert.Equal("UNSUPPORTED_FILE_TYPE",(await Doc(r,false)).RootElement.GetProperty("code").GetString()); }
  [Fact] public async Task Sha256_duplicate_is_detected() { using var f=new SaceFactory(); var c=await Client(f); var id=await DemoOperationId(c); var bytes=Pdf("same"); Assert.Equal("Accepted",(await Bulk(c,id,[("one.pdf",bytes,"application/pdf","OTHER")])).RootElement.GetProperty("files")[0].GetProperty("status").GetString()); var second=await Bulk(c,id,[("copy.pdf",bytes,"application/pdf","OTHER")]); Assert.Equal("DuplicateSkipped",second.RootElement.GetProperty("files")[0].GetProperty("status").GetString()); }
  [Fact] public async Task Multiple_documents_of_same_type_are_allowed() { using var f=new SaceFactory(); var c=await Client(f); var id=await DemoOperationId(c); var result=await Bulk(c,id,[("a.pdf",Pdf("a"),"application/pdf","EDOCUMENT_ACK"),("b.pdf",Pdf("b"),"application/pdf","EDOCUMENT_ACK")]); Assert.Equal(2,result.RootElement.GetProperty("accepted").GetInt32()); var op=await Doc(await c.GetAsync($"/api/operations/{id}")); Assert.Equal(2,op.RootElement.GetProperty("documents").EnumerateArray().Count(x=>x.GetProperty("documentType").GetProperty("code").GetString()=="EDOCUMENT_ACK")); }
  [Theory]
  [InlineData("261631086002948PS01.pdf","PEDIMENTO")]
  [InlineData("054926MFC01.pdf","COMMERCIAL_INVOICE")]
  [InlineData("shipmentPL01.pdf","PACKING_LIST")]
  [InlineData("logisticsTR01.pdf","TRANSPORT_DOCUMENT")]
  [InlineData("acuseCOVE01.pdf","COVE_ACK")]
  [InlineData("despachoQR01.pdf","DODA")]
  public async Task Filename_classification_matches_transparent_rules(string name,string expected) { using var f=new SaceFactory(); var c=await Client(f); var id=await DemoOperationId(c); var analysis=await Analyze(c,id,[(name,Pdf(name),"application/pdf")]); Assert.Equal(expected,analysis.RootElement[0].GetProperty("classification").GetProperty("documentTypeCode").GetString()); }
  [Fact] public async Task Cfdi_uuid_is_extracted() { using var f=new SaceFactory(); var c=await Client(f); var id=await DemoOperationId(c); const string uuid="123E4567-E89B-12D3-A456-426614174000"; var xml=$"<cfdi:Comprobante xmlns:cfdi='http://www.sat.gob.mx/cfd/4' Fecha='2026-07-19T12:00:00' Total='4358.25' Moneda='USD'><cfdi:Emisor Rfc='AAA010101AAA'/><cfdi:Receptor Rfc='BBB010101BBB'/><TimbreFiscalDigital UUID='{uuid}'/></cfdi:Comprobante>"; var result=await Bulk(c,id,[("cfdi.xml",Encoding.UTF8.GetBytes(xml),"application/xml","CUSTOMS_BROKER_INVOICE")]); var docId=result.RootElement.GetProperty("files")[0].GetProperty("documentId").GetGuid(); var detail=await Doc(await c.GetAsync($"/api/operations/{id}/documents/{docId}")); Assert.Contains(detail.RootElement.GetProperty("document").GetProperty("references").EnumerateArray(),x=>x.GetProperty("referenceType").GetString()=="CFDI_UUID"&&x.GetProperty("value").GetString()==uuid); }
  [Fact] public async Task Edocument_reference_is_extracted() { using var f=new SaceFactory(); var c=await Client(f); var id=await DemoOperationId(c); var xml="<DIG_ENVIO><eDocument>0438261HN7ZL7</eDocument></DIG_ENVIO>"; var result=await Bulk(c,id,[("envio.xml",Encoding.UTF8.GetBytes(xml),"application/xml","EDOCUMENT_ACK")]); var docId=result.RootElement.GetProperty("files")[0].GetProperty("documentId").GetGuid(); var detail=await Doc(await c.GetAsync($"/api/operations/{id}/documents/{docId}")); Assert.Contains(detail.RootElement.GetProperty("document").GetProperty("references").EnumerateArray(),x=>x.GetProperty("referenceType").GetString()=="EDOCUMENT"); }
  [Fact] public async Task Bulk_upload_is_partially_successful() { using var f=new SaceFactory(); var c=await Client(f); var id=await DemoOperationId(c); var result=await Bulk(c,id,[("good.pdf",Pdf("ok"),"application/pdf","OTHER"),("empty.xml",[],"application/xml","OTHER")]); Assert.Equal(1,result.RootElement.GetProperty("accepted").GetInt32()); Assert.Equal(1,result.RootElement.GetProperty("rejected").GetInt32()); }
  [Fact] public async Task Existing_demo_operation_still_loads() { using var f=new SaceFactory(); var c=await Client(f); var id=await DemoOperationId(c); var op=await Doc(await c.GetAsync($"/api/operations/{id}")); Assert.Equal("IMP-2026-000001",op.RootElement.GetProperty("folio").GetString()); }
  [Fact] public async Task Existing_demo_audit_still_works() { using var f=new SaceFactory(); var c=await Client(f); var id=await DemoOperationId(c); var audit=await Doc(await c.PostAsync($"/api/operations/{id}/audit",null)); Assert.True(audit.RootElement.GetProperty("reviewed").GetInt32()>=4); }
  [Fact] public async Task Lone_edocument_reference_produces_technical_warning() { using var f=new SaceFactory(); var c=await Client(f); var id=await DemoOperationId(c); var xml="<DIG_ENVIO><eDocument>0438261HN7ZL7</eDocument></DIG_ENVIO>"; await Bulk(c,id,[("envio.xml",Encoding.UTF8.GetBytes(xml),"application/xml","EDOCUMENT_ACK")]); var audit=await Doc(await c.PostAsync($"/api/operations/{id}/audit",null)); Assert.Equal("Completed",audit.RootElement.GetProperty("status").GetString()); var op=await Doc(await c.GetAsync($"/api/operations/{id}")); var latest=op.RootElement.GetProperty("audits").EnumerateArray().OrderByDescending(x=>x.GetProperty("startedAt").GetDateTime()).First(); Assert.Contains(latest.GetProperty("results").EnumerateArray(),x=>x.GetProperty("ruleId").GetString()=="TECH-005"&&x.GetProperty("status").GetString()=="Warning"); }
  [Fact] public async Task Matching_edocument_references_are_technically_valid() { using var f=new SaceFactory(); var c=await Client(f); var id=await DemoOperationId(c); var one="<DIG_ENVIO><eDocument>0438261HN7ZL7</eDocument></DIG_ENVIO>"; var two="<DIG_RECIBO><eDocument>0438261HN7ZL7</eDocument></DIG_RECIBO>"; await Bulk(c,id,[("envio.xml",Encoding.UTF8.GetBytes(one),"application/xml","EDOCUMENT_ACK"),("recibo.xml",Encoding.UTF8.GetBytes(two),"application/xml","OTHER")]); await Doc(await c.PostAsync($"/api/operations/{id}/audit",null)); var op=await Doc(await c.GetAsync($"/api/operations/{id}")); var latest=op.RootElement.GetProperty("audits").EnumerateArray().OrderByDescending(x=>x.GetProperty("startedAt").GetDateTime()).First(); Assert.Contains(latest.GetProperty("results").EnumerateArray(),x=>x.GetProperty("ruleId").GetString()=="TECH-005"&&x.GetProperty("status").GetString()=="Valid"); }
  [Fact] public async Task Correction_and_reaudit_still_work() { using var f=new SaceFactory(); var c=await Client(f); var findings=await Doc(await c.GetAsync("/api/findings")); var finding=findings.RootElement.EnumerateArray().Single(x=>x.GetProperty("folio").GetString()=="IMP-2026-000001"); using var content=FileContent("certificate.pdf",Pdf("certificate"),"application/pdf"); var response=await c.PostAsync($"/api/findings/{finding.GetProperty("id").GetGuid()}/correction",content); var result=await Doc(response); Assert.Equal("Resolved",result.RootElement.GetProperty("findingStatus").GetString()); }

  private static byte[] Pdf(string marker)=>Encoding.UTF8.GetBytes($"%PDF-1.4 synthetic {marker}");
  private static async Task<HttpClient> Client(SaceFactory f){var c=f.CreateClient();var login=await Doc(await c.PostAsJsonAsync("/api/auth/login",new{email="admin@sace.local",password="Admin123!"}));c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",login.RootElement.GetProperty("token").GetString());return c;}
  private static async Task<Guid> DemoOperationId(HttpClient c){var d=await Doc(await c.GetAsync("/api/operations?search=IMP-2026-000001&page=1&pageSize=10"));return d.RootElement.GetProperty("items")[0].GetProperty("id").GetGuid();}
  private static async Task<Guid> TypeId(HttpClient c,string code){var d=await Doc(await c.GetAsync("/api/document-types"));return d.RootElement.EnumerateArray().Single(x=>x.GetProperty("code").GetString()==code).GetProperty("id").GetGuid();}
  private static MultipartFormDataContent FileContent(string name,byte[] bytes,string mime){var form=new MultipartFormDataContent();var data=new ByteArrayContent(bytes);data.Headers.ContentType=new MediaTypeHeaderValue(mime);form.Add(data,"file",name);return form;}
  private static Task<HttpResponseMessage> Single(HttpClient c,Guid id,string name,byte[] bytes,string mime,Guid typeId)=>c.PostAsync($"/api/operations/{id}/documents?documentTypeId={typeId}",FileContent(name,bytes,mime));
  private static async Task<JsonDocument> Analyze(HttpClient c,Guid id,(string name,byte[] bytes,string mime)[] files){using var form=new MultipartFormDataContent();foreach(var f in files){var data=new ByteArrayContent(f.bytes);data.Headers.ContentType=new MediaTypeHeaderValue(f.mime);form.Add(data,"files",f.name);}return await Doc(await c.PostAsync($"/api/operations/{id}/documents/analyze",form));}
  private static async Task<JsonDocument> Bulk(HttpClient c,Guid id,(string name,byte[] bytes,string mime,string code)[] files){using var form=new MultipartFormDataContent();foreach(var f in files){var data=new ByteArrayContent(f.bytes);data.Headers.ContentType=new MediaTypeHeaderValue(f.mime);form.Add(data,"files",f.name);form.Add(new StringContent(f.code),"documentTypeCodes");}form.Add(new StringContent("true"),"skipDuplicate");return await Doc(await c.PostAsync($"/api/operations/{id}/documents/bulk",form));}
  private static async Task<JsonDocument> Doc(HttpResponseMessage r,bool success=true){var text=await r.Content.ReadAsStringAsync();if(success)r.EnsureSuccessStatusCode();return JsonDocument.Parse(text);}
}
