using System.Text;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Sace.Api.Contracts;
using Sace.Api.Domain;
using Sace.Api.Infrastructure;
using Sace.Api.Services;

var builder = WebApplication.CreateBuilder(args);
builder.Logging.ClearProviders(); builder.Logging.AddConsole();
if (builder.Environment.IsDevelopment()) builder.Logging.AddDebug();

var configuredPort = builder.Configuration["PORT"];
if (!string.IsNullOrWhiteSpace(configuredPort))
{
    if (!int.TryParse(configuredPort, out var port) || port is < 1 or > 65535)
        throw new InvalidOperationException("PORT debe ser un número entre 1 y 65535.");
    builder.WebHost.UseUrls($"http://0.0.0.0:{port}");
}

static string ResolvePath(string configuredPath, string contentRoot)
    => Path.GetFullPath(Path.IsPathRooted(configuredPath) ? configuredPath : Path.Combine(contentRoot, configuredPath));

var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
    ?? builder.Configuration.GetConnectionString("Default")
    ?? throw new InvalidOperationException("Falta ConnectionStrings:DefaultConnection.");
var sqlite = new SqliteConnectionStringBuilder(connectionString);
if (!string.IsNullOrWhiteSpace(sqlite.DataSource) && sqlite.DataSource != ":memory:")
{
    var databasePath = ResolvePath(sqlite.DataSource, builder.Environment.ContentRootPath);
    Directory.CreateDirectory(Path.GetDirectoryName(databasePath)
        ?? throw new InvalidOperationException("No se pudo resolver el directorio de SQLite."));
}

var storageRoot = ResolvePath(builder.Configuration["Storage:RootPath"]
    ?? builder.Configuration["FileStorage:RootPath"] ?? "../storage", builder.Environment.ContentRootPath);
Directory.CreateDirectory(storageRoot);
var dataProtectionKeysPath = ResolvePath(builder.Configuration["DataProtection:KeysPath"] ?? ".keys", builder.Environment.ContentRootPath);
Directory.CreateDirectory(dataProtectionKeysPath);

builder.Services.ConfigureHttpJsonOptions(o => { o.SerializerOptions.Converters.Add(new JsonStringEnumConverter()); o.SerializerOptions.ReferenceHandler = System.Text.Json.Serialization.ReferenceHandler.IgnoreCycles; });
builder.Services.AddDataProtection().PersistKeysToFileSystem(new DirectoryInfo(dataProtectionKeysPath));
builder.Services.AddDbContext<SaceDbContext>(o => o.UseSqlite(connectionString, sqliteOptions => sqliteOptions.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery)));
builder.Services.AddHostedService<DailyAuditWorker>();
builder.Services.AddScoped<IPasswordService, PasswordService>(); builder.Services.AddScoped<ITokenService, TokenService>(); builder.Services.AddScoped<IAuditEngine, AuditEngine>(); builder.Services.AddScoped<ILegalAuditEngine, LegalAuditEngine>(); builder.Services.AddScoped<IMonthlyAuditRule, DemoMonthlyConsolidationRule>(); builder.Services.AddScoped<IFileStorageService, LocalFileStorageService>(); builder.Services.AddScoped<IDocumentValidationService, DocumentValidationService>(); builder.Services.AddScoped<IDocumentClassifier, DocumentClassifier>(); builder.Services.AddScoped<IDocumentProcessingService, DocumentProcessingService>(); builder.Services.AddScoped<PedimentoXmlParser>(); builder.Services.AddScoped<IXmlDocumentProcessor>(x => x.GetRequiredService<PedimentoXmlParser>()); builder.Services.AddScoped<IPedimentoParser>(x => x.GetRequiredService<PedimentoXmlParser>()); builder.Services.AddScoped<IPdfDocumentProcessor, PdfDocumentProcessor>(); builder.Services.AddScoped<IExcelDocumentProcessor, ExcelDocumentProcessor>();
var jwtKey = builder.Configuration["Jwt:Key"];
if (string.IsNullOrWhiteSpace(jwtKey) || jwtKey.Length < 32)
    throw new InvalidOperationException("Jwt:Key es obligatorio y debe tener al menos 32 caracteres.");
if (builder.Environment.IsProduction() && (jwtKey.Contains("DEVELOPMENT", StringComparison.OrdinalIgnoreCase) || jwtKey.Contains("CHANGE_ME", StringComparison.OrdinalIgnoreCase) || jwtKey.Contains("CHANGE_THIS", StringComparison.OrdinalIgnoreCase)))
    throw new InvalidOperationException("Jwt:Key no puede usar una clave de demostración en Production.");
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(o => { o.TokenValidationParameters = new TokenValidationParameters { ValidateIssuer = true, ValidIssuer = builder.Configuration["Jwt:Issuer"], ValidateAudience = true, ValidAudience = builder.Configuration["Jwt:Audience"], ValidateLifetime = true, ValidateIssuerSigningKey = true, IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey)), ClockSkew = TimeSpan.FromMinutes(1) }; });
var allowedOrigins = builder.Configuration.GetSection("Cors:AllowedOrigins").Get<string[]>()
    ?? builder.Configuration.GetSection("AllowedOrigins").Get<string[]>()
    ?? (builder.Environment.IsDevelopment() ? ["http://localhost:5173", "http://127.0.0.1:5173"] : []);
if (allowedOrigins.Length == 0) throw new InvalidOperationException("Configure al menos un origen en Cors:AllowedOrigins.");
builder.Services.AddAuthorization(); builder.Services.AddCors(o => o.AddPolicy("configured-origins", p => p.WithOrigins(allowedOrigins).AllowAnyHeader().AllowAnyMethod()));
var maxUploadMb = builder.Configuration.GetValue<long?>("Uploads:MaxFileSizeMb") ?? builder.Configuration.GetValue<long?>("FileStorage:MaxFileSizeMb") ?? 25;
if (maxUploadMb <= 0) throw new InvalidOperationException("Uploads:MaxFileSizeMb debe ser mayor que cero.");
builder.Services.Configure<FormOptions>(o => o.MultipartBodyLengthLimit = checked(maxUploadMb * 1024L * 1024L));
builder.Services.AddEndpointsApiExplorer(); builder.Services.AddSwaggerGen();

var app = builder.Build(); app.UseCors("configured-origins");
if (app.Environment.IsDevelopment() || app.Configuration.GetValue<bool>("Swagger:Enabled")) { app.UseSwagger(); app.UseSwaggerUI(); }
app.Use(async (ctx, next) => { try { await next(); } catch (KeyNotFoundException ex) { await Error(ctx, 404, "NOT_FOUND", ex.Message); } catch (InvalidOperationException ex) { await Error(ctx, 400, "VALIDATION_ERROR", ex.Message); } catch (Exception ex) { app.Logger.LogError(ex, "Unhandled API error"); await Error(ctx, 500, "INTERNAL_ERROR", "Ocurrió un error inesperado."); } });
app.UseAuthentication(); app.UseAuthorization();
app.MapGet("/health", (ILogger<Program> logger) => { logger.LogInformation("Health check completed successfully."); return Results.Ok(new { status = "healthy" }); }).AllowAnonymous();
app.MapGet("/api/health", () => Results.Ok(new { status = "healthy" })).AllowAnonymous();

var auth = app.MapGroup("/api/auth");
auth.MapPost("/login", async (LoginRequest request, SaceDbContext db, IPasswordService passwords, ITokenService tokens) => { var email = request.Email.Trim().ToLowerInvariant(); var user = await db.Users.SingleOrDefaultAsync(x => x.Email == email); if (user is null || !user.IsActive || !passwords.Verify(request.Password, user.PasswordHash)) return Results.Json(new ApiError(401, "INVALID_CREDENTIALS", "Correo o contraseña incorrectos.", new { }), statusCode: 401); db.SystemAuditLogs.Add(new SystemAuditLog { UserId = user.Id, Action = "LOGIN", EntityType = "User", EntityId = user.Id.ToString(), Details = "Inicio de sesión exitoso." }); await db.SaveChangesAsync(); return Results.Ok(new { token = tokens.Create(user), user = new { user.Id, user.Name, user.Email, user.Role } }); }).AllowAnonymous();

var api = app.MapGroup("/api").RequireAuthorization();
api.MapGet("/dashboard", async (SaceDbContext db) => { var month = DateTime.UtcNow.ToString("yyyy-MM"); var ops = await db.TradeOperations.Include(x => x.Findings).Include(x => x.Audits).ThenInclude(x => x.Results).ToListAsync(); var current = ops.Where(x => x.Period == month).ToList(); var open = ops.SelectMany(x => x.Findings).Where(x => x.Status != FindingStatus.Resolved).ToList(); var legalAudits = ops.SelectMany(x => x.Audits.Where(a => a.AuditType == AuditType.Legal).OrderByDescending(a => a.StartedAt).Take(1)).ToList(); var legal = legalAudits.SelectMany(x => x.Results).Where(x => x.IsIncludedInLegalCompliance).ToList(); var decided = legal.Count(x => x.Outcome is LegalOutcome.COMPLIANT or LegalOutcome.NON_COMPLIANT); var compliant = legal.Count(x => x.Outcome == LegalOutcome.COMPLIANT); var applicable = legal.Count(x => x.Outcome != LegalOutcome.NOT_APPLICABLE); return Results.Ok(new { kpis = new { operationsThisMonth = current.Count, imports = current.Count(x => x.OperationType == OperationType.Importacion), exports = current.Count(x => x.OperationType == OperationType.Exportacion), pendingAudit = ops.Count(x => x.Status == OperationStatus.PendingAudit), withFindings = ops.Count(x => x.Findings.Any(f => f.Status != FindingStatus.Resolved)), pendingFindings = open.Count, criticalFindings = open.Count(x => x.Severity == Severity.Critical), legalCompliance = decided == 0 ? (double?)null : Math.Round(compliant * 100d / decided, 1), legalCoverage = applicable == 0 ? 0 : Math.Round(decided * 100d / applicable, 1), legalAuditedOperations = legalAudits.Count }, operationsByStatus = ops.GroupBy(x => x.Status).Select(x => new { name = x.Key, value = x.Count() }), operationsByType = ops.GroupBy(x => x.OperationType).Select(x => new { name = x.Key, value = x.Count() }), findingsBySeverity = open.GroupBy(x => x.Severity).Select(x => new { name = x.Key, value = x.Count() }), latestOperations = ops.OrderByDescending(x => x.OperationDate).Take(6).Select(x => new { x.Id, x.Folio, x.PedimentoNumber, x.OperationType, x.OperationDate, x.Status, findings = x.Findings.Count(f => f.Status != FindingStatus.Resolved) }) }); });

api.MapGet("/operations", async (string? search, OperationType? type, OperationStatus? status, string? period, int page, int pageSize, SaceDbContext db) => { page = Math.Max(page, 1); pageSize = Math.Clamp(pageSize == 0 ? 10 : pageSize, 1, 50); var q = db.TradeOperations.AsNoTracking().Include(x => x.Findings).Include(x => x.Audits).AsQueryable(); if (!string.IsNullOrWhiteSpace(search)) q = q.Where(x => x.Folio.Contains(search) || x.PedimentoNumber.Contains(search)); if (type.HasValue) q = q.Where(x => x.OperationType == type); if (status.HasValue) q = q.Where(x => x.Status == status); if (!string.IsNullOrWhiteSpace(period)) q = q.Where(x => x.Period == period); var total = await q.CountAsync(); var items = await q.OrderByDescending(x => x.OperationDate).Skip((page - 1) * pageSize).Take(pageSize).Select(x => new { x.Id, x.Folio, x.PedimentoNumber, x.OperationDate, x.OperationType, x.Period, x.CustomsRegime, x.IsImmex, x.Status, auditResult = x.Audits.OrderByDescending(a => a.StartedAt).Select(a => a.Results.Any(r => r.Status == ResultStatus.Missing || r.Status == ResultStatus.Invalid) ? "Con hallazgos" : "Correcta").FirstOrDefault(), findings = x.Findings.Count(f => f.Status != FindingStatus.Resolved) }).ToListAsync(); return Results.Ok(new { items, total, page, pageSize, pages = (int)Math.Ceiling(total / (double)pageSize) }); });
api.MapPost("/operations", async (CreateOperationRequest request, HttpContext ctx, SaceDbContext db, IAuditEngine engine) => { if (string.IsNullOrWhiteSpace(request.PedimentoNumber) || string.IsNullOrWhiteSpace(request.Period) || request.OperationDate == default) return Results.BadRequest(new ApiError(400, "VALIDATION_ERROR", "Pedimento, fecha y periodo son obligatorios.", new { })); if (request.PreferentialTreatment && string.IsNullOrWhiteSpace(request.TradeAgreement)) return Results.BadRequest(new ApiError(400, "VALIDATION_ERROR", "Indique el TLC aplicable cuando existe trato preferencial.", new { tradeAgreement = "Requerido" })); var year = request.OperationDate.Year; var prefix = request.OperationType == OperationType.Importacion ? "IMP" : "EXP"; var sequence = await db.TradeOperations.CountAsync(x => x.OperationType == request.OperationType && x.OperationDate.Year == year) + 1; var op = new TradeOperation { Folio = $"{prefix}-{year}-{sequence:D6}", PedimentoNumber = request.PedimentoNumber.Trim(), OperationDate = request.OperationDate.ToUniversalTime(), Period = request.Period, OperationType = request.OperationType, PedimentoKey = request.PedimentoKey, TariffFraction = request.TariffFraction, OriginCountry = request.OriginCountry, DestinationCountry = request.DestinationCountry, CustomsRegime = request.CustomsRegime, IsImmex = request.IsImmex, PreferentialTreatment = request.PreferentialTreatment, TradeAgreement = request.PreferentialTreatment ? request.TradeAgreement : null, CustomsOffice = request.CustomsOffice, InvoiceNumber = request.InvoiceNumber, CommercialValue = request.CommercialValue, Currency = request.Currency, Quantity = request.Quantity, Unit = request.Unit, GrossWeight = request.GrossWeight, CoveNumber = request.CoveNumber, ExchangeRate = request.ExchangeRate, DeclaredCustomsValueMxn = request.DeclaredCustomsValueMxn, Incoterm = request.Incoterm, Nico = request.Nico, GoodsDescription = request.GoodsDescription }; db.TradeOperations.Add(op); db.SystemAuditLogs.Add(Log(ctx.User.UserId(), "OPERATION_CREATED", "TradeOperation", op.Id, $"Expediente {op.Folio} creado.")); await db.SaveChangesAsync(); await engine.ExecuteAsync(op.Id, AuditType.Daily, ctx.User.UserId()); return Results.Created($"/api/operations/{op.Id}", new { op.Id, op.Folio }); });
api.MapPut("/operations/{id:guid}", async (Guid id, CreateOperationRequest request, HttpContext ctx, SaceDbContext db) => { var op = await db.TradeOperations.FindAsync(id); if (op is null) return Results.NotFound(); op.PedimentoNumber=request.PedimentoNumber.Trim(); op.OperationDate=request.OperationDate.ToUniversalTime(); op.Period=request.Period; op.OperationType=request.OperationType; op.PedimentoKey=request.PedimentoKey; op.TariffFraction=request.TariffFraction; op.OriginCountry=request.OriginCountry; op.DestinationCountry=request.DestinationCountry; op.CustomsRegime=request.CustomsRegime; op.IsImmex=request.IsImmex; op.PreferentialTreatment=request.PreferentialTreatment; op.TradeAgreement=request.PreferentialTreatment?request.TradeAgreement:null; op.CustomsOffice=request.CustomsOffice; op.InvoiceNumber=request.InvoiceNumber; op.CommercialValue=request.CommercialValue; op.Currency=request.Currency; op.Quantity=request.Quantity; op.Unit=request.Unit; op.GrossWeight=request.GrossWeight; op.CoveNumber=request.CoveNumber; op.ExchangeRate=request.ExchangeRate; op.DeclaredCustomsValueMxn=request.DeclaredCustomsValueMxn; op.Incoterm=request.Incoterm; op.Nico=request.Nico; op.GoodsDescription=request.GoodsDescription; op.UpdatedAt=DateTime.UtcNow; db.SystemAuditLogs.Add(Log(ctx.User.UserId(), "OPERATION_UPDATED", "TradeOperation", op.Id, $"Expediente {op.Folio} actualizado.")); await db.SaveChangesAsync(); return Results.Ok(op); });
api.MapGet("/operations/{id:guid}", async (Guid id, SaceDbContext db) => { var op = await db.TradeOperations.AsNoTracking().Include(x => x.Documents).ThenInclude(x => x.DocumentType).Include(x => x.Documents).ThenInclude(x => x.References).Include(x => x.Adjustments).Include(x => x.Audits).ThenInclude(x => x.Results).ThenInclude(x => x.DocumentType).Include(x => x.Audits).ThenInclude(x => x.Results).ThenInclude(x => x.NormativeRule).Include(x => x.Findings).ThenInclude(x => x.DocumentType).SingleOrDefaultAsync(x => x.Id == id); return op is null ? Results.NotFound(new ApiError(404, "NOT_FOUND", "Operación no localizada.", new { })) : Results.Ok(op); });
api.MapGet("/operations/{id:guid}/requirements", async (Guid id, IAuditEngine engine) => Results.Ok(await engine.GetRequirementsAsync(id)));
api.MapPost("/operations/{id:guid}/audit", async (Guid id, HttpContext ctx, IAuditEngine engine) => { var audit = await engine.ExecuteAsync(id, AuditType.Daily, ctx.User.UserId()); return Results.Ok(new { audit.Id, audit.Number, audit.Status, audit.CompletedAt, reviewed = audit.Results.Count, valid = audit.Results.Count(x => x.Status == ResultStatus.Valid), errors = audit.Results.Count(x => x.Status == ResultStatus.Invalid), missing = audit.Results.Count(x => x.Status == ResultStatus.Missing), findings = audit.Results.Count(x => x.Status is ResultStatus.Invalid or ResultStatus.Missing) }); });
api.MapPost("/operations/{id:guid}/legal-audit", async (Guid id, HttpContext ctx, ILegalAuditEngine engine, CancellationToken ct) => Results.Ok(await engine.ExecuteAsync(id, ctx.User.UserId(), ct: ct)));
api.MapGet("/operations/{id:guid}/legal-audits", async (Guid id, SaceDbContext db) => Results.Ok(await db.Audits.AsNoTracking().Where(x => x.TradeOperationId == id && x.AuditType == AuditType.Legal).Include(x => x.Results).ThenInclude(x => x.NormativeRule).OrderByDescending(x => x.StartedAt).ToListAsync()));
api.MapGet("/operations/{id:guid}/adjustments", async (Guid id, SaceDbContext db) => Results.Ok(await db.CustomsValueAdjustments.AsNoTracking().Where(x => x.TradeOperationId == id).OrderBy(x => x.CreatedAt).ToListAsync()));
api.MapPost("/operations/{id:guid}/adjustments", async (Guid id, CustomsValueAdjustmentRequest request, HttpContext ctx, SaceDbContext db) => { if (!await db.TradeOperations.AnyAsync(x => x.Id == id)) return Results.NotFound(); if (request.Amount < 0 || string.IsNullOrWhiteSpace(request.Concept) || string.IsNullOrWhiteSpace(request.Currency)) return Results.BadRequest(new ApiError(400, "VALIDATION_ERROR", "Concepto, moneda e importe no negativo son obligatorios.", new { })); if (request.SourceDocumentId.HasValue && !await db.OperationDocuments.AnyAsync(x => x.Id == request.SourceDocumentId && x.TradeOperationId == id)) return Results.BadRequest(new ApiError(400, "INVALID_SOURCE_DOCUMENT", "El documento fuente no pertenece al expediente.", new { })); var item = new CustomsValueAdjustment { TradeOperationId = id, Concept = request.Concept.Trim(), Description = request.Description, Amount = request.Amount, Currency = request.Currency.Trim().ToUpperInvariant(), AdjustmentType = request.AdjustmentType, LegalQualificationStatus = request.LegalQualificationStatus, SourceDocumentId = request.SourceDocumentId }; db.CustomsValueAdjustments.Add(item); db.SystemAuditLogs.Add(Log(ctx.User.UserId(), "CUSTOMS_VALUE_ADJUSTMENT_CREATED", "CustomsValueAdjustment", item.Id, $"{item.Concept}: {item.Amount} {item.Currency}; {item.AdjustmentType}/{item.LegalQualificationStatus}.")); await db.SaveChangesAsync(); return Results.Created($"/api/operations/{id}/adjustments/{item.Id}", item); });
api.MapPost("/audit-results/{id:guid}/manual-review", async (Guid id, ManualReviewRequest request, HttpContext ctx, SaceDbContext db) => { var result = await db.AuditResults.Include(x => x.NormativeRule).SingleOrDefaultAsync(x => x.Id == id && x.Outcome != null); if (result is null) return Results.NotFound(); if (request.ManualOutcome == LegalOutcome.NOT_APPLICABLE || request.ManualOutcome == LegalOutcome.MANUAL_REVIEW || string.IsNullOrWhiteSpace(request.Comment)) return Results.BadRequest(new ApiError(400, "VALIDATION_ERROR", "Seleccione un dictamen final y capture el comentario de revisión.", new { })); result.ManualOutcome = request.ManualOutcome; result.ReviewComment = request.Comment.Trim(); result.ReviewerUserId = ctx.User.UserId(); result.ReviewedAt = DateTime.UtcNow; db.SystemAuditLogs.Add(Log(ctx.User.UserId(), "MANUAL_REVIEW_COMPLETED", "AuditResult", result.Id, $"{result.RuleId}: automático {result.Outcome}; humano {result.ManualOutcome}.")); await db.SaveChangesAsync(); return Results.Ok(result); });

api.MapPost("/operations/{id:guid}/documents", async (Guid id, Guid documentTypeId, IFormFile file, HttpContext ctx, SaceDbContext db, IDocumentProcessingService processing, CancellationToken ct) => { var type = await db.DocumentTypes.FindAsync([documentTypeId], ct); if (type is null) return Results.NotFound(new ApiError(404, "NOT_FOUND", "Tipo documental no localizado.", new { })); var result = await processing.UploadBulkAsync(id, [file], [type.Code], true, ctx.User.UserId(), ct); var item = result.Files[0]; return item.Status == "Accepted" ? Results.Created($"/api/operations/{id}/documents/{item.DocumentId}", item) : Results.BadRequest(new ApiError(400, item.Code ?? "INVALID_FILE", item.Message ?? "Archivo rechazado.", new { item.DuplicateOf })); }).DisableAntiforgery();
api.MapPost("/operations/{id:guid}/documents/analyze", async (Guid id, HttpRequest request, IDocumentProcessingService processing, CancellationToken ct) => { var form = await request.ReadFormAsync(ct); return Results.Ok(await processing.AnalyzeAsync(id, form.Files.ToList(), ct)); }).DisableAntiforgery();
api.MapPost("/operations/{id:guid}/documents/bulk", async (Guid id, HttpRequest request, HttpContext ctx, IDocumentProcessingService processing, CancellationToken ct) => { var form = await request.ReadFormAsync(ct); var codes = form["documentTypeCodes"].Select(x=>x??"").ToArray(); var skip = !bool.TryParse(form["skipDuplicate"].FirstOrDefault(), out var value) || value; return Results.Ok(await processing.UploadBulkAsync(id, form.Files.ToList(), codes, skip, ctx.User.UserId(), ct)); }).DisableAntiforgery();
api.MapGet("/operations/{operationId:guid}/documents/{documentId:guid}", async (Guid operationId, Guid documentId, SaceDbContext db) => { var doc = await db.OperationDocuments.AsNoTracking().Include(x => x.DocumentType).Include(x => x.References).SingleOrDefaultAsync(x => x.Id == documentId && x.TradeOperationId == operationId); if (doc is null) return Results.NotFound(); var cove = await db.TradeOperations.Where(x => x.Id == operationId).Select(x => x.CoveNumber).SingleAsync(); return Results.Ok(new { document = doc, referenceComparisons = doc.References.Select(x => new { x.ReferenceType, x.Value, matchesOperation = x.ReferenceType == "COVE" && !string.IsNullOrWhiteSpace(cove) ? string.Equals(x.Value, cove, StringComparison.OrdinalIgnoreCase) : (bool?)null }) }); });
api.MapPatch("/operations/{operationId:guid}/documents/{documentId:guid}", async (Guid operationId, Guid documentId, UpdateDocumentRequest request, HttpContext ctx, SaceDbContext db) => { var doc = await db.OperationDocuments.Include(x => x.References).SingleOrDefaultAsync(x => x.Id == documentId && x.TradeOperationId == operationId); if (doc is null) return Results.NotFound(); doc.DocumentNumber=request.DocumentNumber; doc.DocumentDate=request.DocumentDate?.ToUniversalTime(); doc.SourceSystem=request.SourceSystem; doc.Notes=request.Notes; foreach(var reference in request.References ?? []) { var type=reference.ReferenceType.Trim().ToUpperInvariant(); var value=reference.Value.Trim().ToUpperInvariant(); if(value.Length>0 && !doc.References.Any(x=>x.ReferenceType==type && x.Value==value)) doc.References.Add(new DocumentReference { ReferenceType=type, Value=value, Source=reference.Source }); } db.SystemAuditLogs.Add(Log(ctx.User.UserId(), "DOCUMENT_METADATA_UPDATED", "OperationDocument", doc.Id, $"Metadata actualizada para {doc.OriginalFileName}.")); await db.SaveChangesAsync(); return Results.Ok(doc); });
api.MapGet("/operations/{operationId:guid}/documents/{documentId:guid}/download", async (Guid operationId, Guid documentId, SaceDbContext db, IFileStorageService storage, CancellationToken ct) => { var doc = await db.OperationDocuments.SingleOrDefaultAsync(x => x.Id == documentId && x.TradeOperationId == operationId, ct); if (doc is null) return Results.NotFound(); var stream = await storage.OpenAsync(doc.FilePath, ct); return stream is null ? Results.NotFound(new ApiError(404, "FILE_NOT_FOUND", "El archivo demo no tiene contenido físico asociado.", new { })) : Results.File(stream, doc.MimeType, doc.OriginalFileName); });

api.MapGet("/findings", async (FindingStatus? status, Severity? severity, CorrectionResponsible? responsible, string? period, SaceDbContext db) => { var q = db.Findings.AsNoTracking().Include(x => x.TradeOperation).Include(x => x.DocumentType).AsQueryable(); if (status.HasValue) q = q.Where(x => x.Status == status); if (severity.HasValue) q = q.Where(x => x.Severity == severity); if (responsible.HasValue) q = q.Where(x => x.CorrectionResponsible == responsible); if (!string.IsNullOrWhiteSpace(period)) q = q.Where(x => x.TradeOperation.Period == period); return Results.Ok(await q.OrderByDescending(x => x.CreatedAt).Select(x => new { x.Id, x.Number, x.TradeOperationId, x.TradeOperation.Folio, x.TradeOperation.PedimentoNumber, document = x.DocumentType.Name, x.RuleId, x.Description, x.Severity, x.CorrectionResponsible, x.Status, x.CreatedAt }).ToListAsync()); });
api.MapGet("/findings/{id:guid}", async (Guid id, SaceDbContext db) => { var item = await db.Findings.AsNoTracking().Include(x => x.TradeOperation).Include(x => x.DocumentType).Include(x => x.History).SingleOrDefaultAsync(x => x.Id == id); return item is null ? Results.NotFound() : Results.Ok(item); });
api.MapPatch("/findings/{id:guid}/status", async (Guid id, ChangeFindingStatusRequest request, HttpContext ctx, SaceDbContext db) => { var finding = await db.Findings.Include(x => x.History).SingleOrDefaultAsync(x => x.Id == id); if (finding is null) return Results.NotFound(); var valid = (finding.Status, request.Status) is (FindingStatus.Pending, FindingStatus.InCorrection) or (FindingStatus.InCorrection, FindingStatus.Resolved); if (!valid) return Results.BadRequest(new ApiError(400, "INVALID_TRANSITION", $"No se permite cambiar de {finding.Status} a {request.Status}.", new { })); var previous = finding.Status; finding.Status = request.Status; finding.UpdatedAt = DateTime.UtcNow; if (request.Status == FindingStatus.Resolved) finding.ResolvedAt = DateTime.UtcNow; db.FindingHistories.Add(new FindingHistory { FindingId = finding.Id, PreviousStatus = previous, NewStatus = request.Status, Comment = request.Comment ?? "Estado actualizado.", ChangedBy = ctx.User.UserId() }); db.SystemAuditLogs.Add(Log(ctx.User.UserId(), "FINDING_STATUS_CHANGED", "Finding", finding.Id, $"{previous} → {request.Status}")); await db.SaveChangesAsync(); return Results.Ok(new { finding.Id, finding.Status }); });
api.MapPost("/findings/{id:guid}/correction", async (Guid id, IFormFile file, HttpContext ctx, SaceDbContext db, IDocumentProcessingService processing, IAuditEngine engine, CancellationToken ct) => { var finding = await db.Findings.Include(x => x.DocumentType).SingleOrDefaultAsync(x => x.Id == id, ct); if (finding is null) return Results.NotFound(); if (finding.Status == FindingStatus.Resolved) return Results.BadRequest(new ApiError(400, "INVALID_TRANSITION", "El hallazgo ya está resuelto.", new { })); var uploaded = await processing.UploadBulkAsync(finding.TradeOperationId, [file], [finding.DocumentType.Code], false, ctx.User.UserId(), ct); var item = uploaded.Files[0]; if (item.Status != "Accepted") return Results.BadRequest(new ApiError(400, item.Code ?? "INVALID_FILE", item.Message ?? "Archivo rechazado.", new { })); if (finding.Status == FindingStatus.Pending) { db.FindingHistories.Add(new FindingHistory { FindingId = finding.Id, PreviousStatus = FindingStatus.Pending, NewStatus = FindingStatus.InCorrection, Comment = "Corrección iniciada al cargar una nueva versión.", ChangedBy = ctx.User.UserId() }); finding.Status = FindingStatus.InCorrection; await db.SaveChangesAsync(ct); } var audit = await engine.ExecuteAsync(finding.TradeOperationId, AuditType.Reaudit, ctx.User.UserId(), ct); await db.Entry(finding).ReloadAsync(ct); var version = await db.OperationDocuments.Where(x => x.Id == item.DocumentId).Select(x => x.Version).SingleAsync(ct); return Results.Ok(new { message = finding.Status == FindingStatus.Resolved ? "Documento corregido correctamente. La re-auditoría no encontró inconsistencias. Hallazgo resuelto." : "Documento cargado y re-auditado.", documentVersion = version, auditId = audit.Id, findingStatus = finding.Status }); }).DisableAntiforgery();

api.MapGet("/audits", async (SaceDbContext db) => Results.Ok(await db.Audits.AsNoTracking().OrderByDescending(x => x.StartedAt).Take(100).Select(x => new { x.Id, x.Number, x.AuditType, x.Status, x.TradeOperationId, x.Period, x.StartedAt, x.CompletedAt, results = x.Results.Count }).ToListAsync()));
api.MapGet("/audits/monthly", async (string period, IMonthlyAuditRule rule, CancellationToken ct) => Results.Ok(await rule.EvaluateAsync(period, ct)));
api.MapPost("/audits/monthly", async (string period, HttpContext ctx, SaceDbContext db, IMonthlyAuditRule rule, CancellationToken ct) => { var result = await rule.EvaluateAsync(period, ct); var audit = new Audit { Number = $"AUD-{(await db.Audits.CountAsync(ct) + 1):D6}", Period = period, AuditType = AuditType.Monthly, Status = AuditStatus.Completed, CompletedAt = DateTime.UtcNow, CreatedBy = ctx.User.UserId() }; db.Audits.Add(audit); db.SystemAuditLogs.Add(Log(ctx.User.UserId(), "MONTHLY_AUDIT_EXECUTED", "Audit", audit.Id, $"Periodo {period}; regla DEMO-MONTHLY-001.")); await db.SaveChangesAsync(ct); return Results.Ok(result); });

api.MapGet("/normative-rules", async (SaceDbContext db) => Results.Ok(await db.NormativeRules.AsNoTracking().OrderBy(x => x.Code).ThenByDescending(x => x.Version).ToListAsync()));
api.MapPost("/normative-rules", async (RuleRequest request, HttpContext ctx, SaceDbContext db) => { var code = request.Code.Trim().ToUpperInvariant(); var version = await db.NormativeRules.Where(x => x.Code == code).MaxAsync(x => (int?)x.Version) ?? 0; var rule = new NormativeRule { Code = code, Name = request.Name, NormativeSource = request.NormativeSource, RuleCategory = request.RuleCategory, Description = request.Description, RuleType = request.RuleType, SourceDocument = request.SourceDocument, Article = request.Article, Section = request.Section, Subsection = request.Subsection, RuleNumber = request.RuleNumber, Annex = request.Annex, Appendix = request.Appendix, OfficialUrl = request.OfficialUrl, PublicationDate = request.PublicationDate?.ToUniversalTime(), EffectiveFrom = request.EffectiveFrom.ToUniversalTime(), EffectiveTo = request.EffectiveTo?.ToUniversalTime(), Version = version + 1, IsActive = request.IsActive, AutomationLevel = request.AutomationLevel, RequiresManualReview = request.RequiresManualReview, IsLegalRule = request.IsLegalRule, IsIncludedInLegalCompliance = request.IsIncludedInLegalCompliance, ConfigurationJson = request.ConfigurationJson }; db.NormativeRules.Add(rule); db.SystemAuditLogs.Add(Log(ctx.User.UserId(), "NORMATIVE_RULE_VERSION_CHANGED", "NormativeRule", rule.Id, $"{rule.Code} v{rule.Version}.")); await db.SaveChangesAsync(); return Results.Created($"/api/normative-rules/{rule.Id}", rule); });
api.MapPatch("/normative-rules/{id:guid}/toggle", async (Guid id, HttpContext ctx, SaceDbContext db) => { var rule = await db.NormativeRules.FindAsync(id); if (rule is null) return Results.NotFound(); rule.IsActive = !rule.IsActive; db.SystemAuditLogs.Add(Log(ctx.User.UserId(), "NORMATIVE_RULE_TOGGLED", "NormativeRule", id, $"{rule.Code} v{rule.Version}: {(rule.IsActive ? "activa" : "inactiva")}.")); await db.SaveChangesAsync(); return Results.Ok(rule); });
api.MapGet("/document-types", async (SaceDbContext db) => Results.Ok(await db.DocumentTypes.AsNoTracking().OrderBy(x => x.Name).ToListAsync()));
api.MapPatch("/document-types/{id:guid}", async (Guid id, DocumentType request, HttpContext ctx, SaceDbContext db) => { var item = await db.DocumentTypes.FindAsync(id); if (item is null) return Results.NotFound(); item.Name=request.Name; item.Description=request.Description; item.CorrectionResponsible=request.CorrectionResponsible; item.IsActive=request.IsActive; db.SystemAuditLogs.Add(Log(ctx.User.UserId(), "DOCUMENT_TYPE_UPDATED", "DocumentType", id, $"Catálogo {item.Code} actualizado.")); await db.SaveChangesAsync(); return Results.Ok(item); });
api.MapGet("/audit-log", async (string? action, DateTime? from, DateTime? to, SaceDbContext db) => { var q = db.SystemAuditLogs.AsNoTracking().Include(x => x.User).AsQueryable(); if (!string.IsNullOrWhiteSpace(action)) q = q.Where(x => x.Action.Contains(action)); if (from.HasValue) q = q.Where(x => x.Timestamp >= from); if (to.HasValue) q = q.Where(x => x.Timestamp <= to); return Results.Ok(await q.OrderByDescending(x => x.Timestamp).Take(250).Select(x => new { x.Id, x.Timestamp, user = x.User != null ? x.User.Name : "Sistema", x.Action, x.EntityType, x.EntityId, x.Details }).ToListAsync()); });

await using (var scope = app.Services.CreateAsyncScope())
{
    var database = scope.ServiceProvider.GetRequiredService<SaceDbContext>();
    await database.Database.MigrateAsync();
    app.Logger.LogInformation("Database migrations applied successfully.");
}
await DbSeeder.SeedAsync(app.Services); app.Run();

static SystemAuditLog Log(Guid user, string action, string entity, Guid id, string details) => new() { UserId = user == Guid.Empty ? null : user, Action = action, EntityType = entity, EntityId = id.ToString(), Details = details };
static async Task Error(HttpContext context, int status, string code, string message) { context.Response.StatusCode = status; context.Response.ContentType = "application/json"; await context.Response.WriteAsJsonAsync(new ApiError(status, code, message, new { })); }

public partial class Program { }


