import { useState, type ReactNode } from 'react'
import { NavLink, Outlet, useLocation, useNavigate } from 'react-router-dom'
import { Activity, AlertTriangle, BookOpen, ChevronRight, ClipboardCheck, FileClock, FolderOpen, LayoutDashboard, LogOut, Menu, ShieldCheck, X } from 'lucide-react'

const menu = [
  { to:'/', label:'Dashboard', icon:LayoutDashboard }, { to:'/operations', label:'Operaciones', icon:FolderOpen },
  { label:'Auditorías', icon:ClipboardCheck, children:[{to:'/audits/daily',label:'Auditoría diaria'},{to:'/audits/monthly',label:'Auditoría mensual'}] },
  { to:'/findings', label:'Hallazgos', icon:AlertTriangle }, { to:'/normative-rules', label:'Catálogos normativos', icon:BookOpen }, { to:'/history', label:'Historial', icon:FileClock }
]
export function Layout(){ const [open,setOpen]=useState(false); const nav=useNavigate(); const location=useLocation(); const user=JSON.parse(localStorage.getItem('sace_user')||'{}'); const logout=()=>{localStorage.clear();nav('/login')}; return <div className="min-h-screen bg-slate-50">
  {open&&<button aria-label="Cerrar menú" className="fixed inset-0 z-30 bg-slate-950/40 lg:hidden" onClick={()=>setOpen(false)}/>}<aside className={`fixed inset-y-0 left-0 z-40 w-72 bg-navy-950 text-white transition-transform lg:translate-x-0 ${open?'translate-x-0':'-translate-x-full'}`}>
    <div className="flex h-20 items-center justify-between border-b border-white/10 px-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-teal-500"><ShieldCheck size={23}/></span><div><div className="text-xl font-bold tracking-wide">SACE</div><div className="text-[10px] uppercase tracking-[.16em] text-slate-400">Comercio exterior</div></div></div><button className="lg:hidden" onClick={()=>setOpen(false)}><X/></button></div>
    <nav className="space-y-1 px-4 py-6">{menu.map((item,i)=>item.children?<div key={i} className="pb-2"><div className="flex items-center gap-3 px-3 py-2 text-xs font-semibold uppercase tracking-wider text-slate-500"><item.icon size={17}/>{item.label}</div>{item.children.map(c=><NavLink key={c.to} to={c.to} onClick={()=>setOpen(false)} className={({isActive})=>`ml-7 flex items-center gap-2 rounded-xl px-3 py-2.5 text-sm transition ${isActive?'bg-white/10 font-semibold text-white':'text-slate-400 hover:bg-white/5 hover:text-white'}`}><ChevronRight size={14}/>{c.label}</NavLink>)}</div>:<NavLink key={item.to} to={item.to!} end={item.to==='/'} onClick={()=>setOpen(false)} className={({isActive})=>`flex items-center gap-3 rounded-xl px-3 py-3 text-sm transition ${isActive?'bg-teal-500/15 font-semibold text-teal-300':'text-slate-300 hover:bg-white/5 hover:text-white'}`}><item.icon size={19}/>{item.label}</NavLink>)}</nav>
    <div className="absolute inset-x-4 bottom-5 border-t border-white/10 pt-4"><button onClick={logout} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm text-slate-300 hover:bg-white/5 hover:text-white"><LogOut size={19}/>Cerrar sesión</button></div>
  </aside><div className="lg:pl-72"><header className="sticky top-0 z-20 flex h-20 items-center justify-between border-b border-slate-200/80 bg-white/90 px-4 backdrop-blur sm:px-8"><div className="flex items-center gap-4"><button className="rounded-lg p-2 hover:bg-slate-100 lg:hidden" onClick={()=>setOpen(true)}><Menu/></button><div><p className="text-xs font-medium uppercase tracking-wider text-slate-400">Sistema Auditor</p><h1 className="font-semibold text-navy-900">{titleFor(location.pathname)}</h1></div></div><div className="flex items-center gap-3"><span className="hidden text-right sm:block"><span className="block text-sm font-semibold">{user.name||'Usuario SACE'}</span><span className="block text-xs text-slate-500">{user.email}</span></span><span className="grid h-10 w-10 place-items-center rounded-full bg-navy-900 text-sm font-bold text-white">{(user.name||'US').split(' ').map((x:string)=>x[0]).slice(0,2).join('')}</span></div></header><main className="p-4 sm:p-8"><Outlet/></main></div>
  </div> }
function titleFor(path:string){if(path==='/')return 'Panel ejecutivo';if(path.includes('monthly'))return 'Auditoría mensual';if(path.includes('daily'))return 'Auditoría diaria';if(path.includes('normative'))return 'Catálogos normativos';if(path.includes('findings'))return 'Gestión de hallazgos';if(path.includes('history'))return 'Trazabilidad';return 'Expedientes de operación'}

export function PageHeader({eyebrow,title,description,action}:{eyebrow?:string,title:string,description?:string,action?:ReactNode}){return <div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div>{eyebrow&&<p className="mb-1 text-xs font-bold uppercase tracking-[.18em] text-teal-600">{eyebrow}</p>}<h2 className="text-2xl font-bold tracking-tight text-navy-900 sm:text-3xl">{title}</h2>{description&&<p className="mt-2 max-w-3xl text-sm text-slate-500">{description}</p>}</div>{action}</div>}
export function Badge({value}:{value:string}){const v=value?.toLowerCase();let cls='bg-slate-100 text-slate-700 ring-slate-200';if(v?.includes('valid')||v?.includes('completed')||v?.includes('resuelto')||v==='resolved'||v?.includes('correcta'))cls='bg-emerald-50 text-emerald-700 ring-emerald-200';else if(v?.includes('finding')||v?.includes('hallazgo')||v?.includes('invalid')||v?.includes('faltante')||v==='high'||v==='critical')cls='bg-rose-50 text-rose-700 ring-rose-200';else if(v?.includes('pending')||v?.includes('correction')||v?.includes('warning')||v==='medium')cls='bg-amber-50 text-amber-700 ring-amber-200';else if(v?.includes('audited')||v?.includes('daily')||v?.includes('monthly'))cls='bg-sky-50 text-sky-700 ring-sky-200';return <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ring-inset ${cls}`}><span aria-hidden>{v?.includes('valid')||v?.includes('resolved')?'✓':v?.includes('missing')||v?.includes('invalid')?'✕':'●'}</span>{human(value)}</span>}
export function human(v?:string){const map:Record<string,string>={Importacion:'Importación',Exportacion:'Exportación',PendingAudit:'Pendiente de auditoría',WithFindings:'Con hallazgos',Completed:'Completada',Audited:'Auditada',Draft:'Borrador',Pending:'Pendiente',InCorrection:'En corrección',Resolved:'Resuelto',Valid:'Válido',Invalid:'Con error',Missing:'Faltante',Warning:'Con observaciones',NotApplicable:'No aplica',Daily:'Diaria',Monthly:'Mensual',Reaudit:'Re-auditoría',Company:'Empresa',CustomsBroker:'Agente aduanal',Low:'Bajo',Medium:'Medio',High:'Alto',Critical:'Crítico',Demo:'Demo'};return map[v||'']||v||'—'}
export function Empty({text='No hay información disponible.'}:{text?:string}){return <div className="grid min-h-40 place-items-center p-8 text-center text-sm text-slate-500"><div><Activity className="mx-auto mb-3 text-slate-300"/><p>{text}</p></div></div>}
export function Spinner(){return <span className="inline-block h-5 w-5 animate-spin rounded-full border-2 border-current border-r-transparent"/>}
export const fmtDate=(value?:string)=>value?new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeZone:'UTC'}).format(new Date(value)):'—';
export const fmtDateTime=(value?:string)=>value?new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—';
